config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  f_fish_config:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_fish_prompt:
    src: config/fish/fish_prompt.fish
    dst: ~/.config/fish/functions/fish_prompt.fish
  f_mpv:
    src: config/mpv/mpv.conf
    dst: ~/.config/mpv/mpv.conf
  f_zathura:
    src: config/zathura/zathurarc
    dst: ~/.config/zathura/zathurarc
profiles:
  desktop:
    dotfiles:
    - f_fish_config
    - f_fish_prompt 
    - f_zathura
    - f_mpv
  server:
    dotfiles:
    - f_fish_config
    - f_fish_prompt 

