config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  f_fish_config:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_fish_plugins:
    src: config/fish/fish_plugins
    dst: ~/.config/fish/fish_plugins
  d_fish_functions:
    src: config/fish/functions
    dst: ~/.config/fish/functions
  d_fish_completions:
    src: config/fish/completions
    dst: ~/.config/fish/completions
  d_fish_confd:
    src: config/fish/conf.d
    dst: ~/.config/fish/conf.d
  f_mpv:
    src: config/mpv/mpv.conf
    dst: ~/.config/mpv/mpv.conf
  f_zathura:
    src: config/zathura/zathurarc
    dst: ~/.config/zathura/zathurarc
profiles:
  desktop:
    dotfiles:
    - f_fish_config
    - f_fish_plugins
    - d_fish_functions
    - d_fish_completions
    - d_fish_confd
    - f_zathura
    - f_mpv
  server:
    dotfiles:
    - f_fish_config
    - f_fish_plugins
    - d_fish_functions
    - d_fish_completions
    - d_fish_confd

